name: React App deployment to GCS

on:
  push:
    tags:
      - "[0-9][0-9][0-9][0-9][0-9][0-9][0-9]" # fit version number

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: gcs-test-430622

      - name: Upload files to GCS
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          gsutil -m cp -r ./src/* gs://github-action-test/${VERSION}
